site_name: Django doc
extra_css:
  - stylesheets/fontawesome.css
  - stylesheets/extra.css

extra_javascript:
  - scripts/hello_word.js

theme:
  name: material
  language: es
  font:
    code: Fira Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
    - content.code.select

nav:
  # - Inicio:
  #   - Home: index.md
  - Comenzando:
    - comenzando/crear-una-aplicacion-de-encuestas.md
  - "Configuración": configuracion/otra-base-de-datos.md
    #- configuracion/base-de-datos.md
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg    
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences

copyright: Copyright &copy; 2023 Marco Contreras - Enidev911

extra:
  generator: false